version:  '3.7'
services: 
    laravel-db:
        image: mysql:5.7
        environment: 
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: escuela
            MYSQL_USER: usr.laravel
            MYSQL_PASSWORD: yordyaquiles07
        ports: 
            - 33069:3306
        volumes: 
            - ./database/schemas/:/var/lib/mysql
        networks: 
            laravel_prod_net: 
                ipv4_address: 172.21.100.9
    laravel-prod:
        build:
            context: ./
            dockerfile: Dockerfile
        ports: 
            - 8200:80
        volumes: 
            - ./example-prod:/var/www/
            - ./example-prod/public:/var/www/html
        networks: 
            laravel_prod_net: 
                ipv4_address: 172.21.100.10
        depends_on: 
            - laravel-db
volumes: 
    example-prod:
    database:
networks: 
    laravel_prod_net:
        driver: bridge
        ipam:
            driver: default
            config: 
                - 
                    subnet: 172.21.100.0/24